### ISSUE TITLE
langconv import issue

### ISSUE THREAD

**Issue by stchau4work** [LeungMingTakMilton/ChineseNLP#2]
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from src.util.normalize import *
  File "/Users/steven/Documents/dataMining/NLP/ChineseNLP/src/util/normalize.py", line 6, in <module>
    from langconv import *
ModuleNotFoundError: No module named 'langconv'

**Comment by stchau4work** [comment]
A good stuff to read from 2 to 3
https://docs.python.org/3/howto/pyporting.html

**Comment by LeungMingTakMilton** [comment]
Please try the latest release and let see if the same issue exists. Currently the script only supports python2.7 but I will try my best to make it compatible to python3.
